apiVersion: webhookconfig.keptn.sh/v1alpha1
kind: WebhookConfig
metadata:
  name: webhook-configuration
spec:
  webhooks:
    - type: sh.keptn.event.evaluation.finished
      requests:
        - "curl --request POST --data '{   \"channel\" :
          \"{{.data.project}}--{{.data.service}}\",  \"username\" :
          \"keptn\",   \"blocks\": [    {      \"type\" :
          \"section\",      \"text\" : {        \"type\":
          \"mrkdwn\",        \"text\" : \"*Keptn Evaluation finished:*
          {{.data.result}} ({{.data.evaluation.score}} /
          100)\"      }    },    {      \"type\" : \"section\",      \"text\" :
          {        \"type\": \"mrkdwn\",{   \"channel\" :
          \"{{.data.project}}--{{.data.service}}\",  \"username\" :
          \"keptn\",   \"blocks\": [    {      \"type\" :
          \"section\",      \"text\" : {        \"type\":
          \"mrkdwn\",        \"text\" : \"*Keptn Evaluation finished:*
          {{.data.result}} ({{.data.evaluation.score}} /
          100)\"      }    },    {      \"type\" : \"section\",      \"text\" :
          {        \"type\": \"mrkdwn\",        \"text\" : \"*Project:*
          {{.data.project}}\\n*Stage:* {{.data.stage}}\\n*Service:*
          {{.data.service}}\\n*Details:*
          {{.env.secret_keptnslackrollbackpoc_bridgeurl}}/bridge/evaluation/{{.\
          shkeptncontext}}\"      }    }  ]}      }    }  ]}'
          https://hooks.slack.com/services/{{.env.secret_keptnslackrollbackpoc_\
          token}}"
      envFrom:
        - name: secret_keptnslackrollbackpoc_token
          secretRef:
            name: keptnslackrollbackpoc
            key: token
        - name: secret_keptnslackrollbackpoc_bridgeurl
          secretRef:
            name: keptnslackrollbackpoc
            key: bridgeurl
      subscriptionID: 2a7c19b7-e0ff-4411-b6ca-4585279575e4
